name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-macos
          - os: macos-13
            target: x86_64-macos
          - os: ubuntu-latest
            target: x86_64-linux
          - os: ubuntu-24.04
            target: aarch64-linux
          - os: windows-latest
            target: x86_64-windows

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - name: Setup FFmpeg (macOS)
        if: runner.os == 'macOS'
        run: brew install ffmpeg pkgconf coreutils

      - name: Setup FFmpeg (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libswresample-dev pkg-config

      - name: Setup FFmpeg (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install -y ffmpeg-shared
          set INCLUDE=%INCLUDE%;"C:\ProgramData\chocolatey\lib\ffmpeg-shared\tools\ffmpeg-7.1-full_build-shared\include"
          set LIB=%LIB%;"C:\ProgramData\chocolatey\lib\ffmpeg-shared\tools\ffmpeg-7.1-full_build-shared\lib"

      - name: Build
        run: |
          zig build -Doptimize=ReleaseFast -Dstrip=true
          tar czf glyph-${{ matrix.target }}.tar.gz -C zig-out/bin .
          sha256sum glyph-${{ matrix.target }}.tar.gz > glyph-${{ matrix.target }}.tar.gz.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.target }}
          path: glyph-*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: "write-all"
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: build-artifacts-*
          path: artifacts
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
